// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUNhTcnfRW55osutiqWdbvy0IVcoicoo',
    appId: '1:610782855939:web:8c7aec48f62fceb04cdf36',
    messagingSenderId: '610782855939',
    projectId: 'tasky-app-392e9',
    authDomain: 'tasky-app-392e9.firebaseapp.com',
    storageBucket: 'tasky-app-392e9.firebasestorage.app',
    measurementId: 'G-9MMRFSZ290',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT7KWVWAB4iVhvFer5paXJdrrHc4Dw5rs',
    appId: '1:610782855939:android:e2c981dbabd628024cdf36',
    messagingSenderId: '610782855939',
    projectId: 'tasky-app-392e9',
    storageBucket: 'tasky-app-392e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALbcrlmr3C1AwE6C2fy94e75iiOgrKxX8',
    appId: '1:610782855939:ios:760d8ff33c708e224cdf36',
    messagingSenderId: '610782855939',
    projectId: 'tasky-app-392e9',
    storageBucket: 'tasky-app-392e9.firebasestorage.app',
    iosBundleId: 'com.example.tasky',
  );
}
